version: '3.8'

services:
  web:
    image: sportify:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: always