services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - PYTHONPATH=/app
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_volume: