# Generated by Django 5.1.3 on 2024-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gugun", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gugun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "구군",
                "verbose_name_plural": "구군 목록",
            },
        ),
        migrations.AlterModelTable(
            name="gugun",
            table="gugun",
        ),
    ]
