# Generated by Django 5.1.3 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="카테고리명")),
                (
                    "category_name",
                    models.CharField(max_length=255, verbose_name="종목명"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="종목에 대한 상세 설명을 입력하세요",
                        verbose_name="설명",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="categories.category",
                        verbose_name="상위 종목",
                    ),
                ),
            ],
            options={
                "verbose_name": "종목",
                "verbose_name_plural": "종목 목록",
                "db_table": "category",
                "ordering": ["name"],
            },
        ),
    ]
