# Generated by Django 5.1.3 on 2024-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("road_addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadaddress",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "로드 주소",
                "verbose_name_plural": "로드 주소 목록",
            },
        ),
        migrations.AlterModelTable(
            name="roadaddress",
            table="road_address",
        ),
    ]
