# Generated by Django 5.1.3 on 2024-12-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ctprvn_nm",
                    models.CharField(max_length=20, verbose_name="시/도 이름"),
                ),
            ],
            options={
                "verbose_name": "시/도",
                "verbose_name_plural": "시/도 목록",
                "db_table": "sido",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fclty_nm",
                    models.CharField(max_length=100, verbose_name="시설 이름"),
                ),
                (
                    "fclty_addr",
                    models.CharField(max_length=100, verbose_name="도로명 주소"),
                ),
                (
                    "sido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="regions.sido",
                        verbose_name="시/도",
                    ),
                ),
            ],
            options={
                "verbose_name": "시설",
                "verbose_name_plural": "시설 목록",
                "db_table": "facility",
            },
        ),
    ]
