# Generated by Django 5.1.3 on 2024-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sido",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sido_images/",
                verbose_name="시/도 이미지",
            ),
        ),
    ]
