# Generated by Django 5.1.3 on 2024-12-06 00:31

import regions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_sido_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=regions.models.sido_image_path, verbose_name='시/도 이미지'),
        ),
    ]
