# Generated by Django 5.1.3 on 2024-12-03 04:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="progrm_estbl_wkday_nm",
        ),
        migrations.AddField(
            model_name="program",
            name="progrm_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("MON", "월"),
                    ("TUE", "화"),
                    ("WED", "수"),
                    ("THU", "목"),
                    ("FRI", "금"),
                    ("SAT", "토"),
                    ("SUN", "일"),
                ],
                default=["MON"],
                max_length=100,
                verbose_name="운영 요일",
            ),
        ),
    ]
