# Generated by Django 5.1.3 on 2024-12-03 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_remove_program_progrm_estbl_wkday_nm_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["start_time"],
                "verbose_name": "프로그램",
                "verbose_name_plural": "프로그램 목록",
            },
        ),
        migrations.RemoveField(
            model_name="program",
            name="progrm_estbl_tizn_value",
        ),
        migrations.AddField(
            model_name="program",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(9, 50), verbose_name="종료 시간"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="시작 시간"
            ),
        ),
    ]
