# Generated by Django 5.1.3 on 2024-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sido", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sido",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "시도",
                "verbose_name_plural": "시도 목록",
            },
        ),
        migrations.AlterModelTable(
            name="sido",
            table="sido",
        ),
    ]
