# Generated by Django 5.1.3 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gugun", "0001_initial"),
        ("sido", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dong_name", models.CharField(max_length=20, verbose_name="동명")),
                (
                    "gugun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gugun.gugun",
                        verbose_name="구군",
                    ),
                ),
                (
                    "sido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sido.sido",
                        verbose_name="시도",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
