# Generated by Django 5.1.3 on 2024-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dong", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dong",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "동",
                "verbose_name_plural": "동 목록",
            },
        ),
        migrations.AlterModelTable(
            name="dong",
            table="dong",
        ),
    ]
