# Generated by Django 5.1.3 on 2024-11-26 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("road_addresses", "0002_alter_roadaddress_options_alter_roadaddress_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_name",
                    models.CharField(max_length=255, verbose_name="SPORTS CENTER NAME"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="PHONE NUMBER"),
                ),
                (
                    "road_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="road_addresses.roadaddress",
                        verbose_name="ROAD ADDRESS",
                    ),
                ),
            ],
            options={
                "verbose_name": "스포츠 센터",
                "verbose_name_plural": "스포츠 센터 목록",
                "db_table": "sports_center",
                "ordering": ["-created_at"],
            },
        ),
    ]
