# Generated by Django 5.1.3 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jibun_addresses", "0001_initial"),
        ("road_addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_name",
                    models.CharField(max_length=255, verbose_name="SPORTS CENTER NAME"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="PHONE NUMBER"),
                ),
                (
                    "jibun_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jibun_addresses.jibunaddress",
                        verbose_name="JIBUN ADDRESS",
                    ),
                ),
                (
                    "road_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="road_addresses.roadaddress",
                        verbose_name="ROAD ADDRESS",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
