name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create .env file
        run: |
          echo "DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'" >> .env
          echo "DJANGO_DEBUG=False" >> .env
          echo "DB_NAME='${{ secrets.DB_NAME }}'" >> .env
          echo "DB_USER='${{ secrets.DB_USER }}'" >> .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
          echo "DB_HOST='${{ secrets.DB_HOST }}'" >> .env
          echo "DB_PORT=3306" >> .env

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sportify:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sportify:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create .env file on EC2
            echo "DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'" > .env
            echo "DJANGO_DEBUG=False" >> .env
            echo "DB_NAME='${{ secrets.DB_NAME }}'" >> .env
            echo "DB_USER='${{ secrets.DB_USER }}'" >> .env
            echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
            echo "DB_HOST='${{ secrets.DB_HOST }}'" >> .env
            echo "DB_PORT=3306" >> .env

            # Pull and run the Docker container
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sportify:latest
            docker stop sportify || true
            docker rm sportify || true
            docker run -d --name sportify \
              -p 8000:8000 \
              --env-file .env \
              ${{ secrets.DOCKERHUB_USERNAME }}/sportify:latest