name: Deploy to EC2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Prepare deployment directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 홈 디렉토리로 이동
          cd ~
          
          # 이전 배포 디렉토리 백업 (있다면)
          if [ -d "sportify" ]; then
            if [ -d "sportify_backup" ]; then
              rm -rf sportify_backup
            fi
            mv sportify sportify_backup
          fi
          
          # 새 디렉토리 생성
          mkdir -p sportify
          
          # 권한 설정
          sudo chown -R ubuntu:ubuntu sportify

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ubuntu/sportify"
        strip_components: 0

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 홈 디렉토리로 이동
          cd ~
          
          # sportify 디렉토리로 이동
          cd sportify
          
          # .env 파일 복원 또는 생성
          if [ -f "../sportify_backup/.env" ]; then
            cp ../sportify_backup/.env .
          else
            echo "Creating new .env file..."
            echo "DEBUG=0" >> .env
            echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "DJANGO_ALLOWED_HOSTS=${{ secrets.EC2_HOST }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          fi
          
          # Docker 컨테이너 중지 및 재시작
          if command -v docker compose &> /dev/null; then
            docker compose down || true
            docker compose up --build -d
          else
            docker-compose down || true
            docker-compose up --build -d
          fi
          
          # 이전 백업 정리 (선택사항)
          rm -rf ../sportify_backup