name: Deploy to EC2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # ... (이전 설정들) ...

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/sportify
          
          # .env 파일 생성 또는 업데이트
          cat > .env << EOL
          DEBUG=0
          SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,dev.hufsthon.site,dev.hufsthon.site:8000
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          EOL
          
          # Docker 관련 명령어 실행
          sudo docker compose down
          sudo docker compose up --build -d