name: Build and Push Docker Image

# 워크플로우가 실행될 때를 지정합니다
on:
  push:
    branches: [ "develop" ]  # main 브랜치에 push가 발생할 때
  pull_request:
    branches: [ "develop" ]  # main 브랜치로의 PR이 생성될 때
  workflow_dispatch:      # 수동으로 워크플로우를 실행할 수 있게 합니다

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행됩니다 (AMD64 아키텍처)
    
    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Docker 이미지 빌드 및 푸시
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64  # AMD64 아키텍처용으로만 빌드
          push: true
          tags: dong99u/sportify:latest  # 이미지 태그 지정
          
      # 빌드 결과 알림
      - name: Build Status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Build successful! Image pushed to Docker Hub"
          else
            echo "❌ Build failed"
          fi